### ISSUE TITLE
Fork minstant to fastant

### ISSUE THREAD

**Issue by Xuanwo** [fast/fastrace#21]
Hi, do you think it's a good idea to fork `minstant` into `fastant` and eventually deprecate `minstant`?

**Comment by Xuanwo** [comment]
cc @andylokandy @tisonkun @zhongzc for discussion.

**Comment by andylokandy** [comment]
+1

**Comment by tisonkun** [comment]
Let's do it.

We can replace the web_time dep with jiff and possibly rewrite it with latest Rust. So that re-create our own instant lib.

**Comment by tisonkun** [comment]
https://github.com/tisonkun/fastant Ready for transfer. What do you think?

Still retain the TiKV Authors credits since we don't rewrite it anyway.

**Comment by Xuanwo** [comment]
> [tisonkun/fastant](https://github.com/tisonkun/fastant) Ready for transfer. What do you think?
> 
> Still retain the TiKV Authors credits since we don't rewrite it anyway.

Mostly looks good to me. I want to set the version to `0.1.8` to make it easier for users to migrate.

**Comment by tisonkun** [comment]
Done.

We can start a new issue for migrateing `minstant` to `fastant`.
