### ISSUE TITLE
Adding properties to a Span after it's attached to a future

### ISSUE THREAD

**Issue by fiadliel** [fast/fastrace#32]
Hi,
I've been trying out fastrace, and it's been quite nice to use in many respects. Thanks for working on it!

But one thing I haven't figured out how to do yet:

If I have bound a span to the future, I can't get a handle to that span again, to call `with_property` or `with_properties`. If I create a local child span, I can add properties to that child, but I'd like to actually add them to the parent (the span that's bound to the future).

Use case: I'd like to attach some properties to the _result_ of an async call, e.g. some attributes of the value like success or failure.

Is there an approach I'm missing here, or is it possible to add?

**Comment by andylokandy** [comment]
hi @fiadliel, thank you for trying fastrace out. Adding properties to non-local local parent you mentioned is a current limitation of https://docs.rs/fastrace/latest/fastrace/local/struct.LocalSpan.html#method.add_property . It's possible and I'd like to make it available, but I need to evaluate the impact to other part of the system first.

**Comment by fiadliel** [comment]
I did not expect a PR yet - thanks a lot!
Will be a great help, it's sometimes useful to look for spans with certain properties, and often (most times) monitoring systems don't understand how to look for properties across a subtree of spans.

**Comment by andylokandy** [comment]
New version will this feature is released!
https://crates.io/crates/fastrace/0.7.2
