### ISSUE TITLE
feat: compatible with opentelemetry 0.26

### ISSUE THREAD

**Issue by MrCroxx** [fast/fastrace#44]

**Comment by Xuanwo** [comment]
Let's just bump version of otel. We don't need to support multiple versions of OpenTelemetry.

**Comment by MrCroxx** [comment]
Doing. Let me contribute this. 🥵

**Comment by MrCroxx** [comment]
@Xuanwo You really 7/24 online?

**Comment by Xuanwo** [comment]
> @Xuanwo You really 7/24 online?

It's a normal work day :rofl:

**Comment by MrCroxx** [comment]
> > @Xuanwo You really 7/24 online?
> 
> Today is a normal work day 🤣

No. 😭 Don't remind me that.
